### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by Anton0123** [nathanielxd/MagicHomeAPI#5]
When you make major (breaking) changes like between version 1.2 and 1.4 you should increase the major version number and not the minor version number. And why not keep the older versions on nuget so we can go back when we realise that all our code is broken after updating?

Sorry to sound harsh, I appreciate the work you've put into this but it is annoying when you upgrade a package and then find yourself stuck with work you weren't planning to do in the first place not able to revert easily.

**Comment by nathanielxd** [comment]
Sorry! I did not realise you cannot revert changes on packages from NuGet. I thought that by unlisting the previous versions I'll just disallow people to get the deprecated versions of the library. And yes, I've made quite a lot of important modifications since this was my first package ever and there was a lot to improve.
